# Generated by Django 3.0.1 on 2023-04-14 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Users",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user_id",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("first_name", models.TextField(max_length=255)),
                ("last_name", models.TextField(max_length=255)),
                ("dob", models.DateField()),
                ("email", models.EmailField(max_length=254, unique=True)),
            ],
            options={
                "db_table": "users",
            },
        ),
        migrations.CreateModel(
            name="UserCredentials",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("hashed_password", models.TextField(max_length=255)),
                ("verified", models.BooleanField(default=False)),
                (
                    "user_id",
                    models.ForeignKey(
                        max_length=255,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="account.Users",
                    ),
                ),
            ],
            options={
                "db_table": "user_credentials",
            },
        ),
    ]
