# Generated by Django 3.0.1 on 2023-04-16 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_remove_users_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercredentials',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Users'),
        ),
    ]
