# Generated by Django 3.0.1 on 2023-04-14 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="NewsFeed",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("feed_id", models.AutoField(primary_key=True, serialize=False)),
                ("feed_text", models.TextField()),
                (
                    "user_id",
                    models.ForeignKey(
                        max_length=255,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="account.Users",
                    ),
                ),
            ],
            options={
                "db_table": "news_feed",
            },
        ),
    ]
